highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://emanuelfontelles.github.io/cv
author: Emanuel Fontelles

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: "/cv/"
title: Emanuel's Resume
name: Emanuel Fontelles
email: emanuelfontelles
       @fisica.ufc.br
email_full: mailto:emanuelfontelles
            @fisica.ufc.br
website: emanuelfontelles.github.io
website_full: https://emanuelfontelles.github.io
github: emanuelfontelles
linkedin: emanuelfontelles
tel: +55 85 98958-0740
tel_full: tel:+5585989580740
google_maps: 'https://goo.gl/maps/tbwJ7Nva7i62'
address:
#  street: 44 Perth Street
#  postcode: EH3 5BL
  city: Fortaleza
  state: Ceará
  country: Brazil
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
